# Generated by Django 4.2 on 2024-11-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epg',
            old_name='description',
            new_name='desc',
        ),
    ]
