# Generated by Django 4.2 on 2024-11-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0002_rename_description_epg_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
