# Generated by Django 4.2 on 2024-11-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0003_channel_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='logo',
            new_name='logo_path',
        ),
    ]
